### ISSUE TITLE
[Bug] panic: connection already exists

### ISSUE THREAD

**Issue by Jetereting** [MetaCubeX/ClashX.Meta#38]
使用版本： [Releases] [v1.3.6] [ClashX.Meta.macOS.12.0+.zip]

```bash
panic: connection already exists
goroutine 144798 [running]:
github.com/metacubex/quic-go.(*connMultiplexer).AddConn(0x14000081120, {0x14b4ee080?, 0x140002c8298?})
	github.com/metacubex/quic-go@v0.38.1-0.20230909013832-033f6a2115cf/multiplexer.go:
59 +0x198
github.com/metacubex/quic-go.(*Transport).init.func1()
	github.com/metacubex/quic-go@v0.38.1-0.20230909013832-033f6a2115cf/transport.go:214 +0x318
sync.(*Once).doSlow(0x0?, 0x0?)
	sync/once.go:74 +
0x100
sync.(*Once).Do(...)
	sync/once.go:65
github.com/metacubex/quic-go.(*Transport).init(0x140002b20f0, 0x9c?)
	github.com/metacubex/quic-go@v0.38.1-0.20230909013832-033f6a2115cf/transport.go:181 +0x58
github.com/metacubex/quic-go.(*Transport).dial(0x140002b20f0, {0x1031292e8, 0x103a177e0}, {0x10311fe48, 
0x140007d2c00}, {0x0, 0x0}, 0x0?, 0x0?, 0x0?)
	github.com/metacubex/quic-go@v0.38.1-0.20230909013832-033f6a2115cf/transport.go:167 +0x70
github.com/metacubex/quic-go.(*Transport).Dial(...)
	github.com/metacubex/quic-go@v0.38.1-0.20230909013832-033f6a2115cf/transport.go:154
github.com/Dreamacro/clash/transport/hysteria/transport.(*ClientTransport).QUICDial(0x140003186d0?
, {0x1400000eaf0, 0x3}, {0x140000ae138?, 0x0?}, {0x0, 0x0}, 0x1021ee8b4
?, 0x1400021e457?, {0x0, 
...}, ...)
	
github.com/Dreamacro/clash/transport/hysteria/transport/client.go:82 +0x178
github.com/Dreamacro/clash/transport/hysteria/core.(*Client).connectToServer(0x1400019d900, {0x103126390?, 0x1400013a8a0?})
	github.com/Dreamacro/clash/transport/hysteria/core/client.go
:78 +0x70
github.com/Dreamacro/clash/transport/hysteria/core.(*Client).openStreamWithReconnect(0x1400019d900, {0x103126390, 0x1400013a8a0})
	github.com/Dreamacro/clash/transport/hysteria/core/client.go:172 +0xf0
github.com/Dreamacro/clash/transport/hysteria/core.(*Client).DialTCP(0x1400019d900
, {0x1400062baa0?, 0x14000b228f8?}, {0x103126390, 0x1400013a8a0})
	github.com/Dreamacro/clash/transport/hysteria/core/client.go:202 +0x58
github.com/Dreamacro/clash/adapter/outbound.(*Hysteria).DialContext(0x1400000ce40, {0x103129440?, 0x1400089b110}, 0x0?, {
0x0, 0x0, 0x0})
	github.com/Dreamacro/clash/adapter/outbound/hysteria.go:56 +0x1a4
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(...)
	github.com/Dreamacro/clash/adapter/adapter.go:67
github.com/Dreamacro/clash/adapter.(*Proxy).URLTest(0x140000458c0, {
0x103129440?, 0x1400089b110}, {0x1400021e450, 0x23}, {0x0?, 0x0, 0x20000?}, 0x0)
	github.com/Dreamacro/clash/adapter/adapter.go:248 +0x1f4
github.com/Dreamacro/clash/adapter/provider.(*HealthCheck).execute.func1()
	github.com/Dreamacro/clash/adapter/provider/healthcheck.go:210 +0x174
github.com/Dreamacro/clash/common/batch.(*Batch[...]).Go.func1()
	github.com/Dreamacro/clash/common/batch/batch.go:
52 +0xec
created by github.com/Dreamacro/clash/common/batch.(*Batch[...]).Go in goroutine 65
	github.com/Dreamacro/clash/common/batch/batch.go:43 +0xcc
terminationStatus: 2
terminationReason: NSTaskTerminationReason(rawValue: 1)
```

复现步骤，电脑锁屏一段时间，然后打开就会出现，需要重启软件解决

<img width="451" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/11585188/1849ae04-5114-4e12-82e9-2f39881e1527">

关于的版本不对

<img width="423" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/11585188/58f8b9d8-8993-4f4f-b80c-3f3b34ab73cb">

**Comment by Jetereting** [comment]
<img width="632" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/11585188/3fe856ae-3cad-4e64-b9f4-85c070a16490">

出现频率还是挺高的，同一个 panic

**Comment by Jetereting** [comment]
<img width="323" alt="image" src="https://github.com/MetaCubeX/ClashX.Meta/assets/11585188/9b8357da-182f-4c50-a698-a34ae0de552f">
