### ISSUE TITLE
 URLSessionTask failed with error: Could not connect to the server.

### ISSUE THREAD

**Issue by qixiangcn** [MetaCubeX/ClashX.Meta#4]
ClashX.Meta Version: v1.2.3 (287)，Meta Core: v1.14.3

Mac系统Monterey，Version 12.6.4。

使用过程中突然网络全部不可用（包括国内国外），点击ClashX.Meta，提示“URLSessionTask failed with error: Could not connect to the server.”  无法看到任何配置文件，重新载入配置文件也不行。

只能关闭后重新启动ClashX.Meta才可使用。

**Comment by mrFq1** [comment]
command + O 打开配置目录
看看logs 目录下面有没有崩溃的日志文件

**Comment by qixiangcn** [comment]
> command + O 打开配置目录 看看logs 目录下面有没有崩溃的日志文件

2023/04/16 19:55:43 protocol error: received DATA after END_STREAM
2023/04/16 19:56:26 protocol error: received DATA after END_STREAM
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1727482]
goroutine 11852 [
running]:
io.(*PipeWriter).CloseWithError(...)
	io/pipe.go:181
io.(*PipeWriter).Close(...)
	io/pipe.go:171
github.com/Dreamacro/clash/transport/vmess.(*h2Conn).Close(0xc0003ee960)
	github.com/Dreamacro/clash/transport/vmess/h2.go:87
 +0x22
github.com/Dreamacro/clash/adapter.(*Proxy).URLTest.func2()
	github.com/Dreamacro/clash/adapter/adapter.go:128 +0x22
panic({
0x1c2a820, 0x2743c20})
	runtime/panic.go:884 +0x213
io.(*PipeWriter).CloseWithError(...)
	io/pipe.go:181
io.(*PipeWriter).Close
(...)
	io/pipe.go:171
github.com/Dreamacro/clash/transport/vmess.(*h2Conn).Close(0xc0003ee960)
	github.com/Dreamacro/clash/transport/vmess/h2.go:87 +0x22
net/http.(*persistConn).closeLocked(0xc0000b98c0, {0x1f617c0, 0xc000066ef0})
	net/http/transport.go:2732 +0x130
net/http.(*persistConn).cancelRequest
(0xc0005cc000?, {0x1f642c0?, 0x27936e0?})
	net/http/transport.go:1991
 +0xe5
net/http.(*Transport).cancelRequest(0xc0006dbb80
, {0xc00071f068?}, {0x1f642c0, 0x27936e0})
	net/http/transport.go:
810 +0xee
net/http.(*persistConn).roundTrip(0xc0000b98c0
, 0xc00021d100)
	net/http/transport.go:2684 +0xbac
net/http.(*Transport).roundTrip(0xc0006dbb80, 0xc0003a3700
)
	net/http/transport.go:603 +0x7fa
net/http.(*Transport).RoundTrip(0xc0003a3700?
, 0x1f63bc0?)
	net/http/roundtrip.go:17 +
0x19
net/http.send(0xc0003a3600, 
{0x1f63bc0, 0xc0006dbb80}, 
{0x8?, 0x1d83e60
?, 0x2762420?})
	net/http/client.go:252 +0x5f7
net/http.(*Client).send(0xc0003eeb40, 0xc0003a3600, {0xc0001b02e6?, 
0xd?, 0x2762420?})
	net/http/client.go
:176 +0x9b
net/http.(*Client).do(0xc0003eeb40, 0xc0003a3600)
	net/http/client.go:716 +0x8fb
net/http.(*Client).Do(...)
	net/http/client.go:582
github.com/Dreamacro/clash/adapter.(*Proxy).URLTest(0xc0003f39c0, {0x1f6f348?, 0xc000691170}, {0xc0001b02d0, 0x23})
	github.com/Dreamacro/clash/adapter/adapter.go:158 +0x5dd
github.com/Dreamacro/clash/adapter/provider.(*HealthCheck).check.func1.1()
	github.com/Dreamacro/clash/adapter/provider/healthcheck.go:76 +0x163
github.com/Dreamacro/clash/common/batch.(*Batch[...]).Go.func1()
	github.com/Dreamacro/clash/common/batch/batch.go:52 +0x11e
created by github.com/Dreamacro/clash/common/batch.(*Batch[...]).Go
	github.com/Dreamacro/clash/common/batch/batch.go:43 +0xdb
terminationStatus: 2
terminationReason: NSTaskTerminationReason(rawValue: 1)

**Comment by qixiangcn** [comment]
有好几个类似这个的日志，不知道算不算？

**Comment by wwqgtxx** [comment]
试试更新到最新 alpha 内核，刚修了一下
https://github.com/MetaCubeX/Clash.Meta/commit/47df97322db5e4dc28a4c39441c27b401bf53ca6

**Comment by qixiangcn** [comment]
已经更新，再观察一下。

**Comment by qixiangcn** [comment]
> 试试更新到最新 alpha 内核，刚修了一下
> [MetaCubeX/Clash.Meta@47df973]

更新了之后，今天还是出现了问题。截图和日志如下：

(https://github.com/MetaCubeX/Clash.Meta/commit/47df97322db5e4dc28a4c39441c27b401bf53ca6)
![2023-04-18_14-07-55](https://user-images.githubusercontent.com/10330254/232689109-9fd7fc7a-679c-4c0f-b465-b1e3d1533f19.jpg)

2023/04/18 10:48:43 protocol error: received DATA after END_STREAM
2023/04/18 10:49:11 protocol error: received DATA after END_STREAM
2023/04/18 10:50:19 protocol error: received DATA after END_STREAM
2023/04/18 10:50:55 protocol error: received DATA after END_STREAM
2023/04/18 10:52:03 protocol error: received DATA after END_STREAM
2023/04/18 10:52:42 protocol error: received DATA after END_STREAM
2023/04/18 10:53:23 protocol error: received DATA after END_STREAM
2023/04/18 10:54:27 protocol error: received DATA after END_STREAM
2023/04/18 10:55:00 protocol error: received DATA after END_STREAM
2023/04/18 10:55:45 protocol error: received DATA after END_STREAM
2023/04/18 10:56:39 protocol error: received DATA after END_STREAM
terminationStatus: 9
terminationReason: NSTaskTerminationReason(rawValue: 2)


panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=
0x1 addr=0x0 pc=0x1727482]
goroutine 6739 [running]:
io.(*PipeWriter).CloseWithError(...)
	io/pipe.go:181
io.(*PipeWriter).Close(...)
	io/pipe.go:171
github.com/Dreamacro/clash/transport/vmess.(*h2Conn).Close(0xc0009e1740)
	github.com/Dreamacro/clash/transport/vmess/h2.go:87
 +0x22
github.com/Dreamacro/clash/adapter.(*Proxy).URLTest.func2()
	github.com/Dreamacro/clash/adapter/adapter.go
:128 +0x22
github.com/Dreamacro/clash/adapter.(*Proxy).URLTest(0xc0003fd560, 
{0x1f6f348?, 0xc0001242a0}, {0xc000040840, 0x23
})
	github.com/Dreamacro/clash/adapter/adapter.go:161 +0x61c
github.com/Dreamacro/clash/adapter/provider.(*HealthCheck).check.func1.1()
	github.com/Dreamacro/clash/adapter/provider/healthcheck.go:76 +0x163
github.com/Dreamacro/clash/common/batch.(*Batch[...]).Go.func1
()
	github.com/Dreamacro/clash/common/batch/batch.go:52 +0x11e
created by github.com/Dreamacro/clash/common/batch.(*Batch[...]).Go
	github.com/Dreamacro/clash/common/batch/batch.go:43 +
0xdb
terminationStatus: 2
terminationReason: NSTaskTerminationReason(rawValue: 1)

**Comment by wwqgtxx** [comment]
你这报错行数明显就不是最新版本的代码库编译出来的，请确定你更新了最新的alpha版本

**Comment by qixiangcn** [comment]
> 你这报错行数明显就不是最新版本的代码库编译出来的，请确定你更新了最新的alpha版本

确定。

![image](https://user-images.githubusercontent.com/10330254/232816326-6d1cbdaf-58a2-49e1-90b5-547f9084e620.png)

**Comment by mrFq1** [comment]
> > 你这报错行数明显就不是最新版本的代码库编译出来的，请确定你更新了最新的alpha版本
> 
> 确定。
> 
> ![image](https://user-images.githubusercontent.com/10330254/232816326-6d1cbdaf-58a2-49e1-90b5-547f9084e620.png)

勾选 'Use alpha meta' 后重启  切换到alpha 内核

**Comment by tianzhuwei** [comment]
0918开始 我也遇到了这个问题，已经使用了 alpha版本，还是有问题，操作系统为macOS 14 rc版本，不知道和这个有没有关系。
![image](https://github.com/MetaCubeX/ClashX.Meta/assets/16696364/1d0fd282-de7d-4370-8c7a-bb801e6df99d)

**Comment by tianzhuwei** [comment]
> > 你这报错行数明显就不是最新版本的代码库编译出来的，请确定你更新了最新的alpha版本
> 
> 确定。
> 
> ![image](https://user-images.githubusercontent.com/10330254/232816326-6d1cbdaf-58a2-49e1-90b5-547f9084e620.png)

你的问题解决了么？
